repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: lint with ruff
      - id: ruff
        name: sort imports with ruff
        args: [check, --select, I, --fix]
      - id: ruff-format
        name: format with ruff
